### ISSUE TITLE
Index error on startup in collection2 (v2.3.2)

### ISSUE THREAD

**Issue by emmanuelbuah** [aldeed/meteor-collection2#179]
I get the following index error (on user collection) on app startup 

```
MongoError: Index with pattern: { emails.address: 1 } already exists with different options
    at Object.Future.wait (/httpd/huqoo/www/programs/server/node_modules/fibers/future.js:326:15)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:689:1)
    at packages/aldeed:collection2/collection2.js:61:1
    at /httpd/huqoo/www/programs/server/boot.js:212:5
    - - - - -
    at Object.toError (/httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1286:26
    at Server.Base._callHandler (/httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/httpd/huqoo/www/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
```

Mongo db setup with replicaSet (don't know if that helps) and have no data.

**Comment by aldeed** [comment]
You'll probably want to remove the `index: true` and `unique: true` from that field's schema. Accounts packages already set up a unique index for it I guess.

**Comment by emmanuelbuah** [comment]
@aldeed That did the trick. Thanks. We can close this.

**Comment by emmanuelbuah** [comment]
@aldeed I think I was experiencing a similar issue discussed here https://groups.google.com/forum/#!searchin/meteor-talk/mongo$202.6/meteor-talk/JtddViVERXw/griLdjrNrFUJ. It looks like it has something to do with mongo 2.6 and how indexes are created.

**Comment by aldeed** [comment]
OK. Meteor doesn't support 2.6 yet, but they will in the next release so I'll have to make sure that everything is 2.6-compatible at that time.
