### ISSUE TITLE
User update  throws validation exception

### ISSUE THREAD

**Issue by jasenkoh** [aldeed/meteor-collection2#215]
I have following user schema:

```javascript
Schema.User = new SimpleSchema({
  emails: {
      type: [Object],
      // this must be optional if you also use other login services like facebook,
      // but if you use only accounts-password, then it can be required
      optional: true
  },
  services: {
      type: Object,
      optional: true,
      blackbox: true
  },
  "emails.$.address": {
      type: String,
      regEx: SimpleSchema.RegEx.Email
  },
  "services.$.password": {
    type: String,
    min: 6,
  },
  createdAt: {
      type: Date
  },
  profile: {
      type: Object
  },
  articles: {
      type: [String],
      optional: true
  },
  categories: {
      type: [String],
      optional: true
  }
});
```

And when I want to do:

```javascript
Meteor.users.update({_id: user._id}, {$set: { 'user.articles': articleIds }});
```

I get following exception:

```javascript
I20150423-16:49:16.112(-4)? Exception while invoking method 'bootstrapArticles' Error: When the modifier option is true, validation object must have at least one operator
I20150423-16:49:16.113(-4)?     at checkModifier (packages/aldeed:simple-schema/simple-schema-validation.js:271:1)
I20150423-16:49:16.113(-4)?     at doValidation1 (packages/aldeed:simple-schema/simple-schema-validation.js:321:1)
I20150423-16:49:16.113(-4)?     at doValidation (packages/aldeed:simple-schema/simple-schema-context.js:9:1)
I20150423-16:49:16.113(-4)?     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed:simple-schema/simple-schema-context.js:44:1)
I20150423-16:49:16.113(-4)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:317:1)
I20150423-16:49:16.113(-4)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:154:1)
I20150423-16:49:16.113(-4)?     at app/server/article.js:25:20
I20150423-16:49:16.113(-4)?     at Array.forEach (native)
I20150423-16:49:16.113(-4)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
```

I think I am missing something trivial here :)

**Comment by jasenkoh** [comment]
My bad. In $set I was doing user.articles instead of articles.
