### ISSUE TITLE
Validation Errors in Production vs Debugging

### ISSUE THREAD

**Issue by Siyfion** [aldeed/meteor-collection2#218]
I too am having a similar issue to #89; on my development machine if I provide an invalid email address I get the following exception log:

```
Exception while invoking method 'User.create' Error: Email Address must be a valid e-mail address
     at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
     at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1017:1)
     at createUser (packages/accounts-password/password_server.js:718:1)
     at Object.Accounts.createUser (packages/accounts-password/password_server.js:776:1)
     at [object Object].Meteor.methods.User.create (app/server/collections/users.js:42:27)
     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
     at packages/ddp/livedata_server.js:648:1
Sanitized and reported to the client as: Email Address must be a valid e-mail address [400]
```

And on my production server:

```
Error: Email Address must be a valid e-mail address
    at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
    at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
    at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1017:1)
    at createUser (packages/accounts-password/password_server.js:718:1)
    at Object.Accounts.createUser (packages/accounts-password/password_server.js:776:1)
    at [object Object].Meteor.methods.User.create (app/server/collections/users.js:42:27)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
```

On my development environment I get a nice `Meteor.Error` type received by the client, which I parse and display to the user. On the production environment I simply get an "Internal Server Error".

To reproduce this is attach the User schema defined in the README.md of *this* project and then call:

```javascript
Accounts.createUser({
  username: 'TestUsername',
  email: 'anInvalidEmailAddress',
  password: 'test123',
  profile: {
    name: 'Some random name'
  }
});
```

In a production build it will simply throw an `Internal Server Error` rather than the error in debug `Email Address must be a valid e-mail address [400]`.

In fact the same issue occurs with any of the other user fields, for example if you try to create a username with spaces in it ie. "this is not an allowed username" the same thing occurs.

**Comment by Siyfion** [comment]
@aldeed Sorry to "nag", but I don't suppose you've had a chance to look into this at all have you?

**Comment by aldeed** [comment]
I cannot reproduce this. I created a new Meteor app, added latest collection2 and account-password, and replaced the default JS code with this:

```js
Schema = {};

Schema.UserCountry = new SimpleSchema({
    name: {
        type: String
    },
    code: {
        type: String,
        regEx: /^[A-Z]{2}$/
    }
});

Schema.UserProfile = new SimpleSchema({
    firstName: {
        type: String,
        regEx: /^[a-zA-Z-]{2,25}$/,
        optional: true
    },
    lastName: {
        type: String,
        regEx: /^[a-zA-Z]{2,25}$/,
        optional: true
    },
    birthday: {
        type: Date,
        optional: true
    },
    gender: {
        type: String,
        allowedValues: ['Male', 'Female'],
        optional: true
    },
    organization : {
        type: String,
        regEx: /^[a-z0-9A-z .]{3,30}$/,
        optional: true
    },
    website: {
        type: String,
        regEx: SimpleSchema.RegEx.Url,
        optional: true
    },
    bio: {
        type: String,
        optional: true
    },
    country: {
        type: Schema.UserCountry,
        optional: true
    }
});

Schema.User = new SimpleSchema({
    username: {
        type: String,
        regEx: /^[a-z0-9A-Z_]{3,15}$/
    },
    emails: {
        type: [Object],
        // this must be optional if you also use other login services like facebook,
        // but if you use only accounts-password, then it can be required
        optional: true
    },
    "emails.$.address": {
        type: String,
        regEx: SimpleSchema.RegEx.Email
    },
    "emails.$.verified": {
        type: Boolean
    },
    createdAt: {
        type: Date
    },
    profile: {
        type: Schema.UserProfile,
        optional: true
    },
    services: {
        type: Object,
        optional: true,
        blackbox: true
    },
    // Add `roles` to your schema if you use the meteor-roles package.
    // Option 1: Object type
    // If you specify that type as Object, you must also specify the
    // `Roles.GLOBAL_GROUP` group whenever you add a user to a role.
    // Example:
    // Roles.addUsersToRoles(userId, ["admin"], Roles.GLOBAL_GROUP);
    // You can't mix and match adding with and without a group since
    // you will fail validation in some cases.
    roles: {
        type: Object,
        optional: true,
        blackbox: true
    },
    // Option 2: [String] type
    // If you are sure you will never need to use role groups, then
    // you can specify [String] as the type
    roles: {
        type: [String],
        optional: true
    }
});

Meteor.users.attachSchema(Schema.User);

if (Meteor.isClient) {
  Accounts.createUser({
    username: 'TestUsername',
    email: 'anInvalidEmailAddress',
    password: 'test123',
    profile: {
      name: 'Some random name'
    }
  }, function () {
    console.log(arguments);
  });
}
```

I then tested with `meteor run` and `meteor run --production` and `meteor build` followed by `node main.js` in the bundle. The sanitized error correctly appears on the client in all cases.

If you can provide more specific reproduction steps, I can reopen.

**Comment by patte** [comment]
I might be a little late to the party, but I just stumbled upon the same problem.

I have a method called updateQuestionnaire which does nothing really:
```
  updateQuestionnaire: (modifier, docId) ->
    console.log "updateQuestionnaire"
    Questionnaires.update docId, modifier
```

Questionnaires has the following schema attached, nothing fancy either:
````
_schema =
  title:
    type: String
  id:
    label: 'ID'
    type: String
    index: true
    unique: true
Questionnaires.attachSchema(new SimpleSchema(_schema))
````

When I call updateQuestionnaire (from an AutoForm via type=method-update) I get the following error in the server console
````
I20160502-21:07:34.436(2)? Exception while invoking method 'updateQuestionnaire' MongoError: E11000 duplicate key error index: meteor.questionnaires.$c2_id  dup key: { : "ddd" }
I20160502-21:07:34.437(2)?     at Object.Future.wait (/Users/patte/.meteor/packages/meteor-tool/.1.3.2_4.1xmwrdm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:420:15)
I20160502-21:07:34.437(2)?     at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
I20160502-21:07:34.437(2)?     at MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:49)
I20160502-21:07:34.437(2)?     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)
I20160502-21:07:34.437(2)?     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
I20160502-21:07:34.437(2)?     at [object Object].update (packages/mongo/collection.js:568:29)
I20160502-21:07:34.438(2)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
I20160502-21:07:34.438(2)?     at [object Object].Meteor.methods.updateQuestionnaire (lib/collections/questionnaires.coffee:72:20)
I20160502-21:07:34.438(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160502-21:07:34.438(2)?     at packages/ddp-server/livedata_server.js:711:19
I20160502-21:07:34.438(2)?     - - - - -
I20160502-21:07:34.438(2)?     at Object.toError (/Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20160502-21:07:34.439(2)?     at /Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
I20160502-21:07:34.439(2)?     at /Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1197:7
I20160502-21:07:34.439(2)?     at /Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
I20160502-21:07:34.439(2)?     at Server.Base._callHandler (/Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
I20160502-21:07:34.439(2)?     at /Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
I20160502-21:07:34.439(2)?     at [object Object].MongoReply.parseBody (/Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20160502-21:07:34.439(2)?     at [object Object].<anonymous> (/Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
I20160502-21:07:34.439(2)?     at [object Object].emit (events.js:95:17)
I20160502-21:07:34.440(2)?     at [object Object].<anonymous> (/Users/patte/.meteor/packages/npm-mongo/.1.4.43.ht52zb++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

But on the client the error arrives like this:
<img width="1013" alt="screen shot 2016-05-02 at 21 17 37" src="https://cloud.githubusercontent.com/assets/3500621/14965033/5669a574-10ab-11e6-9506-6eb09b7da822.png">

I think It might not even be a problem of C2, but maybe of meteor? Does somebody have an idea?

**Comment by semeano** [comment]
I'm having the same issue. Is there a way to get the proper exception details on the client?
