### ISSUE TITLE
Skip validation option for Accounts.createUser();

### ISSUE THREAD

**Issue by drew-y** [aldeed/meteor-collection2#219]
When Meteor is first run I create an admin user in the fixtures.js file.
```javascript
if ( Meteor.users.find().count() === 0 ) {
  //create initial admin user
  var adminId = Accounts.createUser({
    username: 'admin',
    password: 'password',
    profile: {
        firstName: 'Admin',
        lastName: 'User'
    },
  });
  //We add the user to the admin role with alanning/meteor-roles package
  Roles.addUsersToRoles(adminId, ['admin']);
}
```
The trouble is that in the users schema I define a custom validation rule that prevents users who are not admins from adding users to the admin role.
```javascript
Schema.User = new SimpleSchema({
  username: {
    type: String,
    min: 3,
  },
  services: {
    type: Object,
    optional: true,
    blackbox: true
  },
  profile: {
    type: Schema.UserProfile,
    optional: true
  },
  roles: {
    type: [String],
    optional: true,
    //Prevent user from being added to admin or teacher roles unless the current user is an admin
    custom: function () {
      //check to see if there is an index for the admin role i.e. user is trying to add the admin role
      var hasAdmin = _.indexOf(this.value, 'admin') > -1;
      if (hasAdmin && !isAdmin()) { //the isAdmin() function tests if the current user is in the admin role
        return 'notAllowed'
      }
    }
  }
});
```
So there is a minor catch 22. Also the isAdmin() function uses Meteor.userId() which for some odd reason appears to be running through a Meteor publish function giving me this error:
```shell
W20150504-14:13:44.757(-6)? (STDERR) /Users/andrewyoungwerth/.meteor/packages/meteor-tool/.1.1.3.16w7cie++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150504-14:13:44.758(-6)? (STDERR) 						throw(ex);
W20150504-14:13:44.758(-6)? (STDERR) 						      ^
W20150504-14:13:44.758(-6)? (STDERR) Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
W20150504-14:13:44.758(-6)? (STDERR)     at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1)
W20150504-14:13:44.758(-6)? (STDERR)     at Object.Meteor.user (packages/accounts-base/accounts_server.js:24:1)
W20150504-14:13:44.758(-6)? (STDERR)     at isAdmin (app/lib/permissions.js:2:21)
W20150504-14:13:44.758(-6)? (STDERR)     at Object.Schema.User.SimpleSchema.roles.custom (app/collections/users.js:111:33)
W20150504-14:13:44.758(-6)? (STDERR)     at packages/aldeed:simple-schema/simple-schema-validation.js:170:1
W20150504-14:13:44.758(-6)? (STDERR)     at Array.every (native)
W20150504-14:13:44.758(-6)? (STDERR)     at Function._.every._.all (packages/underscore/underscore.js:219:1)
W20150504-14:13:44.759(-6)? (STDERR)     at validate (packages/aldeed:simple-schema/simple-schema-validation.js:169:1)
W20150504-14:13:44.759(-6)? (STDERR)     at checkObj (packages/aldeed:simple-schema/simple-schema-validation.js:227:1)
W20150504-14:13:44.759(-6)? (STDERR)     at packages/aldeed:simple-schema/simple-schema-validation.js:313:1
``` 
I do not get this when the server already has an admin account and I can add admins normally, even with the validation. It would be nice if I could just skip validation for fixture data all together.

**Comment by drew-y** [comment]
So I solved this issue by taking out the custom validation on the roles field and abstracting out all addUsersToRoles functions into meteor methods. Don't know why it wasn't so obvious to me earlier.
