### ISSUE TITLE
Your app is crashing...Error, title is required...

### ISSUE THREAD

**Issue by studiorooster** [aldeed/meteor-collection2#225]
I've dug around to try and find the answer to this before posting but am not finding my particular error. I built my first app, which runs great locally, so I deployed to myapp.meteor.com, but when visiting the site, it always crashes. I checked the logs and it prints out a string of error information that points to 'Title is required'.

Not seeing the error locally, I did a 'meteor reset' and when restarting the server, was able to reproduce the error. Below is the error shown in localhost, not sure if you need the meteor log, but I can add if it would help. Thank you for your help.
```
Your app is crashing. Here's the latest log.


/Users/Rooster/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Title is required
    at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
    at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
    at Function.Factory._create (packages/dburles:factory/lib/factory.js:79:1)
    at Function.Factory.create (packages/dburles:factory/lib/factory.js:87:1)
    at app/server/seeds/items.js:11:15
    at Function._.times (packages/underscore/underscore.js:1093:1)
    at [object Object]._.(anonymous function) [as times] (packages/underscore/underscore.js:1149:1)
    at app/server/seeds/items.js:10:11
    at /Users/Rooster/Documents/development/pbs/qc-app/.meteor/local/build/programs/server/boot.js:229:5
Exited with code: 8
Your application is crashing. Waiting for file change.```

**Comment by studiorooster** [comment]
Ok, I got it working. I had a startup factory function to pre-populate my app with data and apparently this was causing the error on deployment. Removing it cleared my errors.
