### ISSUE TITLE
Double and float type Numbers

### ISSUE THREAD

**Issue by create** [aldeed/meteor-collection2#248]
Hi,

Please enlighten me if there is way to add double or floating type Numbers. When I specify Number in the Schema it only accepts integers. Thanks.
```
    price: {
        type: Number,
        label: "Price",
        min: 0.0
    }
```

```
W20150810-03:53:41.004(0)? (STDERR) Error: Price must be an integer
W20150810-03:53:41.004(0)? (STDERR)     at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
W20150810-03:53:41.004(0)? (STDERR)     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
W20150810-03:53:41.004(0)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
```

**Comment by create** [comment]
Found that you can specify it to be a decimal in simple-schema documentation. Please add to meteor-collection2 documentation. Thanks!
