### ISSUE TITLE
Pass postId with AutoValue to relate one collection with another

### ISSUE THREAD

**Issue by yudaprama** [aldeed/meteor-collection2#259]
I'm using flow router by @arunoda

It have api to get paramId of current route:
```
// route def: /apps/:appId
// url: /apps/this-is-my-app

var appId = FlowRouter.getParam("appId"); // prints "this-is-my-app"
```

I have 2 collections: `Posts` and `Comments`. I have post with route `http://localhost:3000/post/gPXFJpXwLcg2Ne2Yw`. 

```
FlowRouter.getParam("id");  // prints "gPXFJpXwLcg2Ne2Yw"
```

In each single post, I insert comment with autoform. To relate comments to their post, it will easier to use postId. I use autovalue to get postId

```
Schemas.Comment = new SimpleSchema({
  postId: {
    type: String,
    regEx: SimpleSchema.RegEx.Id,
    autoValue: function() {
      return FlowRouter.getParam('id');
    },
  },
})
```

But I got error once I click comment submit in console `Meteor.error` and terminal:
```
Exception while invoking method '/Comments/insert' TypeError: Object [object Object] has no method 'getParam'
at Object.runAV (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1181:1)
at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1282:1
at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1281:1
at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
at [object Object].getAutoValues (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1244:1)
at [object Object].SimpleSchema.clean (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1648:1)
at c.deny.insert (packages/aldeed_collection2/packages/aldeed_collection2.js:532:1)
```

Any chance to make it work together? This will great so we can relate one collection with another without using nested object or array

Thanks

**Comment by bruhyan** [comment]
Hi do you have the solution to this problem? i am trying to associate comments to respective post id as well
