### ISSUE TITLE
Error Logging reference field schema label, not db value / object name

### ISSUE THREAD

**Issue by cowFipps** [aldeed/meteor-collection2#278]
I'm not sure this is really an issue, so feel free to mark it as a question. I found (by accident) when a label is set to a blank space (i.e., label: " "), the error log doesn't refer to the object name instead of the label. I found this when trying to load fixture data after mongo reset. I know that it's not an undefined or null value so it's not a bug, but I wonder if the logging should refer to 'name' in this case?

Field schema definition:
```javascript
    name: {
        type: String,
        max: 200,
        label: " ",
    }
```

Console output:
```
Error:   is required
at getErrorObject (packages/aldeed_collection2/packages/aldeed_collection2.js:371:1)
at [object Object].doValidate (packages/aldeed_collection2/packages/aldeed_collection2.js:354:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2/packages/aldeed_collection2.js:155:1)
```

**Comment by aldeed** [comment]
I gave it some thought, but I will not make any changes. It may be that someone wants a label that is whitespace for some strange reason.
