### ISSUE TITLE
strange issue while testing

### ISSUE THREAD

**Issue by savvopoulos** [aldeed/meteor-collection2#307]
I get the following error when running meteor test-packages:
W20160210-10:08:38.957(1)? (STDERR) The package aldeed:collection2 at 0.1.7 is incompatible with Meteor 0.9.0 or later.
W20160210-10:08:38.958(1)? (STDERR) If a new, compatible version of this package exists, running 'meteor update' should cause you to update.

Meanwhile, my versions file seems to be fine:
aldeed:collection2@2.8.0
aldeed:collection2-core@1.0.0

This is preventing my tests from passing. Any thoughts on how to address?

Thank you
-Chris

**Comment by savvopoulos** [comment]
Btw, the problem I'm seeing in the tests is this:

TypeError: Object [object Object] has no method 'attachSchema'
    at initUserCollection (user.js:49:8)
    at ArianaMain.init (main.js:14:5)

(which could also be because of a missing dependency, although I triple checked.)

**Comment by savvopoulos** [comment]
meteor show --show-all aldeed:collection2 confirms this:

  0.1.7   August 5th, 2014      installed
  2.8.0   December 30th, 2015   installed

**Comment by savvopoulos** [comment]
adding an explicit dep to collection2@2.8.0 fixes this
