### ISSUE TITLE
Adding meteor-collection2 to an existing app. Can I have schema-less collections living alongside schema-enforced ones?

### ISSUE THREAD

**Issue by juliomac** [aldeed/meteor-collection2#336]
I am trying to add aldeed's package to an existing app.

I am planning to add schemas gradually to each collection. The problem is that I am getting the error on a collection I have not yet attached any schema to:

``Exception while invoking method 'EditAvailability' Error: When the modifier option is true, validation object must have at least one operator
?     at checkModifier (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2293:1)
?     at doValidation1 (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2343:1)
?     at doValidation (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2758:1)
?     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2793:1)
?     at [object Object].doValidate (packages/aldeed_collection2/lib/collection2.js:278:1)
?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2/lib/collection2.js:83:1)
?     at [object Object].EditAvailability (server/serverMethods.js:230:18)
?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
?     at packages/ddp-server/livedata_server.js:711:19
?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
``

Once added the package, Is collection2 required on all collections? Can I have schema-less collections living alongside schema-enforced ones?

**Comment by juliomac** [comment]
Answer is YES.
