### ISSUE TITLE
Collection2 and a users schema breaks a recent update on accounts-server

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-collection2#344]
[This PR](https://github.com/meteor/meteor/pull/7534) (which got merged and published), as [I noted here](https://github.com/meteor/meteor/issues/6462#issuecomment-238855636) is blocked by C2 whenever a schema is attached to the users collection.

The following update on the users document (every 10 minutes by default)

```js
Ap._expirePasswordResetTokens = function (oldestValidDate, userId) {
  var tokenLifetimeMs = this._getPasswordResetTokenLifetimeMs();

  // when calling from a test with extra arguments, you must specify both!
  if ((oldestValidDate && !userId) || (!oldestValidDate && userId)) {
    throw new Error("Bad test. Must specify both oldestValidDate and userId.");
  }

  oldestValidDate = oldestValidDate ||
    (new Date(new Date() - tokenLifetimeMs));
  var userFilter = userId ? {_id: userId} : {};

  this.users.update(_.extend(userFilter, {
    $or: [
      { "services.password.reset.when": { $lt: oldestValidDate } },
      { "services.password.reset.when": { $lt: +oldestValidDate } }
    ]
  }), {
    $pull: {
      "services.password.reset": {
        $or: [
          { when: { $lt: oldestValidDate } },
          { when: { $lt: +oldestValidDate } }
        ]
      }
    }
  }, { multi: true });
}
```

Throws the following error:

```js
Exception in setInterval callback: Error: After filtering out keys not in the schema, your modifier is now empty
    at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:374:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:173:1)
    at AccountsServer.Ap._expirePasswordResetTokens (packages/accounts-base/accounts_server.js:1137:14)
    at packages/accounts-base/accounts_server.js:1174:14
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

When the users document has the following schema attached:

```js
Meteor.users.attachSchema(new SimpleSchema({
  createdAt: {
    type: Date,
  },
  'services.resume.loginTokens.$.when': {
    type: Date,
    optional: true,
  },
  'services.resume.loginTokens.$.hashedToken': {
    type: String,
    optional: true,
  },
  'services.password.bcrypt': {
    type: String,
  },
  'services.password.srp': {
    type: Object,
    blackbox: true,
    optional: true,
  },
  'services.password.reset.token': {
    type: String,
    optional: true,
  },
  'services.password.reset.email': {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
    optional: true,
  },
  'services.password.reset.when': {
    type: Date,
    optional: true,
  },
  'emails.$.address': {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
  },
  'emails.$.verified': {
    type: Boolean,
  },
  'services.email.verificationTokens.$.token': {
    type: String,
    optional: true,
  },
  'services.email.verificationTokens.$.address': {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
    optional: true,
  },
  'services.email.verificationTokens.$.when': {
    type: Date,
    optional: true,
  },
}));
```

**Comment by serkandurusoy** [comment]
@aldeed I did some more investigation and it seems, the latest update on the accounts-server make it impossoble to attach a schema to the users document.

Do you think there's a collection2 option that should allow us to work around this?

**Comment by tmeasday** [comment]
@serkandurusoy did you try adding an object key to the schema for `services.password.reset`?

**Comment by serkandurusoy** [comment]
nope, I had already tried that without success.

Sent from my iPhone



On Aug 15, 2016, at 4:15, Tom Coleman <notifications@github.com> wrote:

@serkandurusoy <https://github.com/serkandurusoy> did you try adding an
object key to the schema for services.password.reset?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aldeed/meteor-collection2/issues/344#issuecomment-239711685>,
or mute the thread

**Comment by tmeasday** [comment]
Actually I think the whole thing was a bug in meteor code. Hopefully it'll
be fixed in the next release of accounts password

**Comment by serkandurusoy** [comment]
Thanks @tmeasday  for getting to the bottom of this.
