### ISSUE TITLE
attaching an schema "Error: Invalid definition for __esModule field."

### ISSUE THREAD

**Issue by Jerolan** [aldeed/meteor-collection2#345]
Hello everyone, I'm trying to insert a schema to my model , I am using meteor 1.4, and I 'm getting this error

```
W20160822-21:10:21.450(-5)? (STDERR) C:\Users\oscje\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160822-21:10:21.465(-5)? (STDERR)                                            throw(ex);
W20160822-21:10:21.470(-5)? (STDERR)                                            ^
W20160822-21:10:21.474(-5)? (STDERR)
W20160822-21:10:21.482(-5)? (STDERR) Error: Invalid definition for __esModule field.
W20160822-21:10:21.486(-5)? (STDERR)     at packages/aldeed_simple-schema/simple-schema.js:457:1
W20160822-21:10:21.490(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20160822-21:10:21.494(-5)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema/simple-schema.js:454:1)
W20160822-21:10:21.500(-5)? (STDERR)     at [object Object].c2AttachSchema [as attachSchema] (packages/aldeed_collection2-core/lib/collection2.js:31:1)
W20160822-21:10:21.504(-5)? (STDERR)     at meteorInstall.imports.api.collections.foodCategories.js (imports/api/collections/foodCategories.js:8:16)
W20160822-21:10:21.511(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160822-21:10:21.516(-5)? (STDERR)     at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160822-21:10:21.524(-5)? (STDERR)     at Module.Mp.import (C:\Users\oscje\AppData\Local\.meteor\packages\modules\0.7.5\npm\node_modules\reify\lib\runtime.js:70:16)
```

**Comment by lmaddio** [comment]
How looks your schema?

**Comment by aldeed** [comment]
Closing old issues. Please comment if this is still an issue and should be reopened.
