### ISSUE TITLE
can't update array

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [aldeed/meteor-collection2#349]
hi, 
```
schema : votes: {
        type: Array,
        label: "Votes",
        autoValue: function () {
            return []
        }
    },
    "votes.$": {
        type: String
    },
```
meteor server method :
```
updatePost: (post)=> {
        console.log(post)
        if (post.vote) {
            let userId = Meteor.user()._id

            if (post.vote == true) {
                Comments.update({_id: post.id}, {$addToSet: {votes: userId}});
            } else {
                Comments.update({_id: post.id}, {
                    $pull: {votes: userId}
                });

            }
        }
        else {
            Comments.update({_id: post.id}, {
                $set: {header: post.header, text: post.text}
            });
        }
    }
```
```
Exception while invoking method 'updatePost' MongoError: Cannot update 'votes' and 'votes' at the same time
I20160907-14:12:04.247(3)?     at Object.Future.wait (/home/v/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20160907-14:12:04.247(3)?     at MongoConnection.<anonymous> (packages/meteor/helpers.js:119:1)
I20160907-14:12:04.247(3)?     at MongoConnection.meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.each.MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:771:49)
I20160907-14:12:04.248(3)?     at [object Object].update (packages/mongo/collection.js:589:29)
I20160907-14:12:04.248(3)?     at [object Object]._.each.Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:203:1)
I20160907-14:12:04.248(3)?     at [object Object].updatePost (server/methods.js:18:26)
I20160907-14:12:04.248(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160907-14:12:04.248(3)?     at packages/ddp-server/livedata_server.js:711:19
I20160907-14:12:04.248(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160907-14:12:04.249(3)?     at packages/ddp-server/livedata_server.js:709:40
I20160907-14:12:04.249(3)?     - - - - -
I20160907-14:12:04.249(3)?     at Function.MongoError.create (/home/v/.meteor/packages/npm-mongo/.1.5.48.1u6dcha++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
I20160907-14:12:04.249(3)?     at toError (/home/v/.meteor/packages/npm-mongo/.1.5.48.1u6dcha++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:114:22)
I20160907-14:12:04.249(3)?     at /home/v/.meteor/packages/npm-mongo/.1.5.48.1u6dcha++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1042:67
I20160907-14:12:04.249(3)?     at /home/v/.meteor/packages/npm-mongo/.1.5.48.1u6dcha++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:430:18
I20160907-14:12:04.250(3)?     at nextTickCallbackWith0Args (node.js:420:9)
I20160907-14:12:04.250(3)?     at process._tickCallback (node.js:349:13)
```

somebody please explain, what I did wrong? 

PS db.comments.update({_id: 'z5nm6TPQJbLWatzET'}, {$addToSet: {votes: 'mySyQtzywgYz5Jr5u'}})  works fine from console.

**Comment by vitaliy-kuzmich** [comment]
upd: now it clear votes array in db, when I try to update it, but I did not touch the schema...

**Comment by vitaliy-kuzmich** [comment]
my fault, wrong userId field declared via let but should var
